### ISSUE TITLE
PHP error on Autoresponder Config page

### ISSUE THREAD

**Issue by vasilii-b** [ebizmarts/magento2-mandrill#17]
url `../admin/system_config/edit/section/autoresponder/key/aa8ae337d.../`

```php
1 exception(s):
Exception #0 (Exception): Notice: Use of undefined constant php - assumed 'php' in /path/to/domain//public_html/school/app/code/Ebizmarts/AutoResponder/view/adminhtml/templates/system/config/birthday/fieldset/hint.phtml on line 10

Exception #0 (Exception): Notice: Use of undefined constant php - assumed 'php' in /path/to/domain//public_html/school/app/code/Ebizmarts/AutoResponder/view/adminhtml/templates/system/config/birthday/fieldset/hint.phtml on line 10
#0 /path/to/domain//public_html/school/app/code/Ebizmarts/AutoResponder/view/adminhtml/templates/system/config/birthday/fieldset/hint.phtml(10): Magento\Framework\App\ErrorHandler->handler(8, 'Use of undefine...', '/home/dev/domai...', 10, Array)
#1 /path/to/domain//public_html/school/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/dev/domai...')
#2 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Ebizmarts\AutoResponder\Block\Adminhtml\System\Config\Birthday\Fieldset\Hint), '/home/dev/domai...', Array)
#3 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/dev/domai...')
#4 /path/to/domain//public_html/school/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#5 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#6 /path/to/domain//public_html/school/app/code/Ebizmarts/AutoResponder/Block/Adminhtml/System/Config/Birthday/Fieldset/Hint.php(50): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form/Element/AbstractElement.php(453): Ebizmarts\AutoResponder\Block\Adminhtml\System\Config\Birthday\Fieldset\Hint->render(Object(Magento\Framework\Data\Form\Element\Text))
#8 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form/Element/Text.php(43): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#9 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form/Element/AbstractElement.php(467): Magento\Framework\Data\Form\Element\Text->getHtml()
#10 /path/to/domain//public_html/school/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(81): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#11 /path/to/domain//public_html/school/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(62): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#12 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form/Element/AbstractElement.php(453): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#13 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form/Element/AbstractElement.php(467): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#14 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form.php(322): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#15 /path/to/domain//public_html/school/vendor/magento/framework/Data/Form.php(337): Magento\Framework\Data\Form->toHtml()
#16 /path/to/domain//public_html/school/vendor/magento/module-backend/Block/Widget/Form.php(98): Magento\Framework\Data\Form->getHtml()
#17 /path/to/domain//public_html/school/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#18 /path/to/domain//public_html/school/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/dev/domai...')
#19 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/home/dev/domai...', Array)
#20 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/dev/domai...')
#21 /path/to/domain//public_html/school/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#22 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#23 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#25 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#26 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#27 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#28 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#29 /path/to/domain//public_html/school/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#30 /path/to/domain//public_html/school/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/dev/domai...')
#31 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/dev/domai...', Array)
#32 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/dev/domai...')
#33 /path/to/domain//public_html/school/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#34 /path/to/domain//public_html/school/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#35 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#36 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#37 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#38 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#39 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#40 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#41 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#42 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#43 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#44 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#45 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#46 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#47 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#48 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#49 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#50 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#51 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#52 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#53 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#54 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#55 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#56 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#57 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#58 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#59 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#60 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#61 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#62 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#63 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#64 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#65 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#66 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#67 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#68 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#69 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#70 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#71 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#72 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#73 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#74 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#75 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#76 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#77 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#78 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#79 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#80 /path/to/domain//public_html/school/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#81 /path/to/domain//public_html/school/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#82 /path/to/domain//public_html/school/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#83 /path/to/domain//public_html/school/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#84 /path/to/domain//public_html/school/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#85 /path/to/domain//public_html/school/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#86 /path/to/domain//public_html/school/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#87 /path/to/domain//public_html/school/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#88 {main}
````

**Comment by SantiParagarino** [comment]
Hello @vasilii-b,

This is related to [AutoResponder](https://github.com/ebizmarts/magento2-autoresponder) module not Mandrill.

Regards,

**Comment by vasilii-b** [comment]
OK then, sorry for the issue here.

**Comment by centerax** [comment]
This issue was moved to ebizmarts/magento2-autoresponder#6
