### ISSUE TITLE
Class 'Mandrill' not found

### ISSUE THREAD

**Issue by michaeldyl520** [ebizmarts/magento2-mandrill#28]
What can I do?
```
[21-Mar-2017 03:50:18 UTC] PHP Fatal error:  Uncaught Error: Class 'Mandrill' not found in /home/dyl/website/m2/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php:31
Stack trace:
#0 /home/dyl/website/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Ebizmarts\Mandrill\Model\Api\Mandrill->__construct(Object(Ebizmarts\Mandrill\Helper\Data))
#1 /home/dyl/website/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Ebizmarts\\Mandr...', Array)
#2 /home/dyl/website/m2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Ebizmarts\\Mandr...')
#3 /home/dyl/website/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Ebizmarts\\Mandr...')
#4 /home/dyl/website/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->reso in /home/dyl/website/m2/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31
```

**Comment by gonzaloebiz** [comment]
composer require mandrill/mandrill

**Comment by michaeldyl520** [comment]
Ok,thank you! @gonzaloebiz
