### ISSUE TITLE
Uncaught Error: Class 'Mandrill' not found in

### ISSUE THREAD

**Issue by MostafaBalata** [ebizmarts/magento2-mandrill#35]
In line 31 $this->_api = new \Mandrill($apiKey); mandrill class is not imported!

`Fatal error: Uncaught Error: Class 'Mandrill' not found in /Applications/MAMP/htdocs/magento2/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php:31 Stack trace: #0 /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(111): Ebizmarts\Mandrill\Model\Api\Mandrill->__construct(Object(Ebizmarts\Mandrill\Helper\Data)) #1 /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Ebizmarts\\Mandr...', Array) #2 /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Ebizmarts\\Mandr...') #3 /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Ebizmarts\\Mandr...') #4 /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/ObjectManager in /Applications/MAMP/htdocs/magento2/app/code/Ebizmarts/Mandrill/Model/Api/Mandrill.php on line 31`

**Comment by MostafaBalata** [comment]
Ummm, I should `run composer require mandrill/mandrill`

referance
https://github.com/ebizmarts/magento2-mandrill/issues/11
