### ISSUE TITLE
Mailchimp Magento version 2.1.4 integration. 

### ISSUE THREAD

**Issue by rujenshakya** [ebizmarts/magento2-mandrill#40]
When i subscribe to newsletter after using the extension i am getting following error. Can you please help. 
```
Trace: #0 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Newsletter\Model\Subscriber->subscribe('coolrujen@hotma...')
#1 /home/lyndylou/public_html/var/generation/Magento/Newsletter/Model/Subscriber/Interceptor.php(247): Magento\Newsletter\Model\Subscriber\Interceptor->___callPlugins('subscribe', Array, Array)
#2 /home/lyndylou/public_html/vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php(124): Magento\Newsletter\Model\Subscriber\Interceptor->subscribe('coolrujen@hotma...')
#3 /home/lyndylou/public_html/var/generation/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(24): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#4 /home/lyndylou/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute()
#5 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#7 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'contextPlugin')
#8 /home/lyndylou/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'customer-app-ac...')
#11 /home/lyndylou/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'storeCheck')
#14 /home/lyndylou/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'weee-app-action...')
#17 /home/lyndylou/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'tax-app-action-...')
#20 /home/lyndylou/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /home/lyndylou/public_html/var/generation/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(39): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /home/lyndylou/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#27 /home/lyndylou/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#30 /home/lyndylou/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#33 /home/lyndylou/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/lyndylou/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#36 /home/lyndylou/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /home/lyndylou/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/lyndylou/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#39 /home/lyndylou/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#40 /home/lyndylou/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#41 /home/lyndylou/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#42 {main} [] []
```

Thanks.

**Comment by centerax** [comment]
what error message do you receive? there is no error message on the trace you provided.
